#+TITLE: Python Exercises
#+OPTIONS: toc:nil

* Python Exercises
:PROPERTIES:
:UNNUMBERED: notoc
:END:

#+TOC: headlines

* Overview
This repository contains the work I did as I learned the Python
programming language. Python was the first language I learned,
starting in 2010. I worked with two beginning programming books based
around Python at various times between 2010 and 2015. /Hello World!/
by Sande discusses language structures, basic algorithms, graphical
interfaces, object oriented programming, and more. This is the book
from which I learned programming for the first time, and I recommend
it to any other interested kids.

Another book, /Python for Kids/ by Briggs, offers slightly different
perspective and priorities in its curriculum, but covers the same
general range of topics. It helped to solidify my knowledge of
Python. I wrote a lot of programs out of interest alone as well as the
exercises from both books. Later on, I also wrote several programs to
do various calculations for high school assignments.

My most recent Python exercises were solutions to problem sets from
Harvard's CS50. Two problem sets require solutions in Python, as an
example of a higher level language than C. Many ideas can be expressed
more concisely and the standard library is absolutely immense, but as
an interpreted language, these qualities come at the cost of greater
execution time.

* /Hello World!/
These exercises are in =hello-world=. Several directories within hold
exercises divided into categories; many other exercises are not
sorted. Some example programs taken down from the text are present, as
well as many end of chapter exercises. All these programs were written
years ago, mostly in Python 2.5, and I have converted them all to
Python 3. In =hello-world/unconverted= are the original files.

* /Python for Kids/
These exercises are in =python-for-kids=. Since this book placed a
much greater emphasis on using the read-evaluate-print loop (REPL) to
learn, there are fewer exercises. Most of these are simple graphical
programs, and there are a couple of games too.

* CS50x
Python is part of the curriculum for this great class, and the problem
sets are in =cs50=. All of the Python files in these directories are
my own work. Other resources were provided as part of the problem
sets. In =cs50/pset7= is a solution that connected Python and SQL.

* Other
The =other= directory holds all the Python work I have done outside of
a book or a class. These programs were written at various times from
2012 to 2017, so some have had to be converted to Python 3. In
=other/friend= are several programs I exchanged in elementary school
with a friend of mine when he was learning Python as well.
